// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Count00: typeof import('./src/components/exercise/Count00.vue')['default']
    Count01: typeof import('./src/components/exercise/Count01.vue')['default']
    Count02: typeof import('./src/components/exercise/Count02.vue')['default']
    Vue3Grammer: typeof import('./src/components/exercise/Vue3Grammer.vue')['default']
  }
}

export { }
