Component({
  properties:{
    list:{
      type:Array,
      value:[]
    }
  },
  methods:{
    handleActive(e){
      console.log(e)
      this.triggerEvent("handlechange",{
        id:e.target.dataset.idkey
      })
    }
  }
})